apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  labels:
    app: website-argocd-k8s-githubactions-kustomize-kyverno03
    version: v1
type: Opaque
data:
  host: cG9zdGdyZXMtc2VydmljZQ==  # postgres-service
  database: ZGF2dHJvX2Ri         # davtro_db
  username: ZGF2dHJv             # davtro
  password: cGFzc3dvcmQxMjM=     # password123
