apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: website-argocd-k8s-githubactions-kustomize-kyverno03-monitor
  namespace: davtro
  labels:
    app: website-argocd-k8s-githubactions-kustomize-kyverno03
    version: v1
spec:
  selector:
    matchLabels:
      app: website-argocd-k8s-githubactions-kustomize-kyverno03
  endpoints:
    - port: http-metrics # Używamy nazwy portu zamiast numeru
      path: /metrics
      interval: 30s
