apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: davtro-website-app
  namespace: argocd
spec:
  project: default
  source:
    path: ./manifests/production
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: davtro
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
