apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: davtro

resources:
- ../base

images:
- name: website-argocd-k8s-githubactions-kustomize-kyverno03
  newName: ghcr.io/exea-centrum/website-argocd-k8s-githubactions-kustomize-kyverno03/website-argocd-k8s-githubactions-kustomize-kyverno03
  newTag: 09f4170535b0f09c2ff61d7f831d862abcdcd5e2
