apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: davtro
  labels:
    app: website-argocd-k8s-githubactions-kustomize-kyverno03
    version: v1
type: Opaque
data:
  host: cG9zdGdyZXMtc2VydmljZQ==  # postgres-service
  database: ZGF2dHJvX2Ri         # davtro_db
  username: ZGF2dHJv             # davtro
  password: cGFzc3dvcmQxMjM=     # password123
---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
  namespace: davtro
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJZV1J0YVc0Nk1ERXpORGs9IgogICAgfQogIH0KfQ==
