apiVersion: v1
kind: ServiceAccount
metadata:
  name: website-argocd-k8s-githubactions-kustomize-kyverno03-sa
  namespace: davtro
  labels:
    app: website-argocd-k8s-githubactions-kustomize-kyverno03
    version: v1
imagePullSecrets:
- name: ghcr-pull-secret
