apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-argocd-k8s-githubactions-kustomize-kyverno03
  namespace: davtro
  labels:
    app: website-argocd-k8s-githubactions-kustomize-kyverno03
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website-argocd-k8s-githubactions-kustomize-kyverno03
  template:
    metadata:
      labels:
        app: website-argocd-k8s-githubactions-kustomize-kyverno03
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: website-argocd-k8s-githubactions-kustomize-kyverno03-sa
      containers:
      - name: website
        image: ghcr.io/exea-centrum/website-argocd-k8s-githubactions-kustomize-kyverno03:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "davtro"
        - name: DB_PASSWORD
          value: "password123"
        - name: DB_NAME
          value: "davtro_db"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
