name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

#on:
#  push:
#    branches:
#      - main
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/website-argocd-k8s-githubactions-kustomize-kyverno03
  KUSTOMIZE_PATH: ./manifests/production

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Prepare Go modules
        run: |
          cd src
          go mod tidy
          go mod download

      - name: Build Go application
        run: |
          cd src
          go build -v ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix={{branch}}-
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update-manifests:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name != 'pull_request'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GHCR_PAT }}

      - name: Update Kustomize image
        run: |
          cd manifests/production
          kustomize edit set image website-argocd-k8s-githubactions-kustomize-kyverno03=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add manifests/production/kustomization.yaml
          git diff --staged --quiet || git commit -m "ci: Update image to ${{ github.sha }}"
          git push
